version: "3"
services:
  redis:
    image: redis
    networks:
      - webnet
    env_file:
      - ./server/.env
  server:
    build: ./server
    expose:
      - 5000
    ports:
      - "5000:5000"
    networks:
      - webnet
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    volumes:
      - ./server:/wise-old-man/server
      - /wise-old-man/server/node_modules
    command: ["npm", "run", "test"]
networks:
  webnet:
volumes:
  pgdata:
