version: "3"
services:
    redis:
        image: redis
        networks: 
            - webnet
        env_file:
            - ./server/.env
    db:
        image: postgres
        networks: 
            - webnet
        volumes:
            - pgdata:/var/lib/postgresql/data
        env_file:
            - ./server/.env
        expose:
            - "5432"
    web:
        image: wise-old-man/server
        ports:
            - "5000:5000"
        networks:
            - webnet
        depends_on:
            - db
            - redis
        environment:
            DB_HOST: db
            REDIS_HOST: redis
        command: ["./wait-for-it.sh", "-t", "30", "db:5432", "--", "npm", "run", "dev"]
networks:
    webnet:
volumes:
    pgdata: