version: "3"
services:
    redis:
        image: redis
        networks: 
            - webnet
        env_file:
            - ./server/.env
    db:
        image: postgres
        networks: 
            - webnet
        volumes:
            - pgdata:/var/lib/postgresql/data
        env_file:
            - ./server/.env
        expose:
            - "5432"
    server:
        image: wise-old-man/server
        ports:
            - "5000:5000"
        networks:
            - webnet
        depends_on:
            - db
            - redis
        environment:
            DB_HOST: db
            REDIS_HOST: redis
        command: ["./wait-for-it.sh", "-t", "30", "db:5432", "--", "npm", "run", "dev"]
    app:
        image: wise-old-man/app
        networks:
            - webnet
        expose:
            - 3000
        ports:
            - 3000:3000
        environment:
            REACT_APP_API_BASE_URL: http://192.168.99.100:5000
networks:
    webnet:
volumes:
    pgdata: