version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: 'Update npm'
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "./server/package-lock.json" }}
      - run:
          name: 'Install dependencies'
          command: cd server && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "./server/package-lock.json" }}
          paths:
            - ./server/node_modules
      - run:
          name: 'Run tests'
          command: cd server && npm run test
    environment:
      DB_DIALECT: sqlite
      DB_STORAGE: ./__tests__/database.sqlite
workflows:
  build-and-test:
    jobs:
      - build-and-test
