version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: 'Install dependencies'
                command: cd server && npm install
            - run:
                name: 'Run tests'
                command: cd server && npm run test
    environment:
      DB_DIALECT: sqlite
      DB_STORAGE: ./__tests__/database.sqlite
      REDIS_HOST: localhost
      REDIS_PORT: 6379
workflows:
  build-and-test:
    jobs:
      - build-and-test
