name: Rebuild Docker Images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
   
  build-server:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Server Docker image
      run: |
        VERSION=$(date +%s)
        cd server
        docker build . --file Dockerfile --tag psikoi/wise-old-man_server:${VERSION}
        docker push psikoi/wise-old-man_server:${VERSION}
