name: Rebuild Docker Images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
   
  build-server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Server Docker image
      run: |
        cd server
        docker build . --file Dockerfile --tag psikoi/wise-old-man_server:latest
        docker push psikoi/wise-old-man_server:latest
           
  build-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the App Docker image
      run: |
        cd app
        docker build . --file Dockerfile --tag psikoi/wise-old-man_app:latest
        docker push psikoi/wise-old-man_app:latest

  build-website:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Website Docker image
      run: |
        cd website
        docker build . --file Dockerfile --tag psikoi/wise-old-man_website:latest
        docker push psikoi/wise-old-man_website:latest

